config/routes.rb
Rails.application.routes.draw do
  root 'battles#new'

  resources :battles, only: [:show, :create, :destroy] do
    resources :comments, only: :create
  end

  resources :battles, only: [:new, :show, :create, :update] do
    post :count, on: :collection
  end

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'sessions/destroy', to: 'sessions#destroy'
  get 'auth/failure', to: 'battles#new'
end

app/models/battle.rb
class Battle < ActiveRecord::Base
  attr_accessor :count

  ITERATIONS_COUNT = 5
  EXECUTION_MAX_TIME = 25 # sec

  validates :before, :after, presence: true
  validates :result, presence: true, unless: :count

  has_many :comments, class_name: 'Comment', foreign_key: :head_battle_id
  has_one :comment, class_name: 'Comment', foreign_key: :comment_battle_id

  def compare
    Timeout::timeout(EXECUTION_MAX_TIME) do
      Benchmark.bm do |x|
        x.report('before') { ITERATIONS_COUNT.times { eval(before) } }
        x.report('after')  { ITERATIONS_COUNT.times { eval(after) } }
      end
    end
  rescue Exception => e
    e.message
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validate :text_or_battle?
  belongs_to :head_battle, class_name: 'Battle'
  belongs_to :comment_battle, class_name: 'Battle'
  belongs_to :user

  accepts_nested_attributes_for :comment_battle, allow_destroy: true

  private

  def text_or_battle?
    if comment_battle&.invalid?
      self.comment_battle = nil
      self.valid?
      errors.add(:comment, 'Comment should have Battle, Text or both.') if text.empty?
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :uid, presence: true

  has_many :comments

  def self.github(request)
    find_or_initialize_by(uid: request['uid']).tap do |user|
      user.email = request.dig('info', 'email')
      user.nickname = request.dig('info', 'nickname')
      user.name = request.dig('info', 'name')
      user.image = request.dig('info', 'image')
      user.url = request.dig('extra', 'raw_info', 'html_url')
      user.token = request.dig('credentials', 'token')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def current_user
    @current_user = User.find(session['user_id']) if session['user_id']
  rescue ActiveRecord::RecordNotFound
    reset_session
  end
  helper_method :current_user
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  def new
    @battle = Battle.new
  end

  def show
    @battle = Battle.find(params[:id])
    @comments = @battle.comments
    @comment = Comment.new
    @comment.build_comment_battle
  end

  def create
    @battle = Battle.new(battle_params)
    @battle.save
  end

  def count
    @battle = Battle.new(battle_params)
    @battle.count = true
    if @battle.valid?
      @battle.result = @battle.compare.to_json
    end
  end

  private

  def battle_params
    params[:battle].merge!(user_id: current_user&.id)
    params.require(:battle).permit!
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :current_user
  before_action :current_battle

  def create
    @comment = Comment.new(comment_params)
    @comment.save
    @comments = @battle.comments
  end

  private

  def current_battle
    @battle = Battle.find(params[:battle_id])
  end

  def comment_params
    params[:comment].merge!(head_battle_id: @battle.id, user_id: current_user.id)
    params[:comment][:comment_battle_attributes].merge!(before: @battle.before)
    params.require(:comment).permit(:text, :head_battle_id, :user_id, comment_battle_attributes: [:before, :after, :result])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.send(env['omniauth.auth']['provider'], env['omniauth.auth'])
    if user.save
      session['user_id'] = user.id
      flash[:success] = 'Logged in!'
    else
      flash[:error] = 'Ferification was failed!'
    end
    redirect_to :root
  end

  def destroy
    reset_session
    redirect_to :root, flash: { success: 'Logged Out!' }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert(flash_type)
    case flash_type.to_sym
    when :success
      'alert-success'
    when :error
      'alert-error'
    when :primary
      'alert-primary'
    when :warning
      'alert-warning'
    else
      flash_type.to_s
    end
  end
end

app/helpers/battle_helper.rb
module BattleHelper
  def display_result(battle)
    result = JSON.parse(battle.result)
    battle.comment ? result[1..-1] : result
  end
end

app/views/battles/_error_code.html.slim
center
  h3.center-align
    ' Please check your Before and After code!
  br
  .card-panel.red.lighten-3
    = "ERROR: #{result}"

app/views/battles/_get_link_form.html.slim
.col.s6.offset-s3
  = simple_form_for battle, remote: true, html: { id: 'get_link_form', class: 'center-align' } do |f|
    = f.input :before, as: :hidden
    = f.input :after, as: :hidden
    = f.input :result, as: :hidden
    = f.submit 'get link!', class: 'btn'

app/views/battles/_provide_battle_link.html.slim
#url-block.center-align
  .card.blue-grey.darken-1.z-depth-5
    .card-content.white-text
      span.card-title
        ' Share link
      .card-action
        p Your battle was saved. You can copy link and share.
        #link-icon data-clipboard-target='url' data-clipboard-text='Default clipboard text from attribute' title='Copy to clipboard.'
          i.material-icons.small.md-dark
            | insert link
        #url
          = battle_url(@battle)

javascript:
  var client = new ZeroClipboard( document.getElementById("link-icon") );

app/views/battles/_table_result.html.slim
table.bordered
  tr
    th
      | Label
    th
      | User
    th
      | System
    th
      | Total
    th
      | Real
  - result.each do |bm|
    tr
      td
        = bm['label']
      td
        = bm['utime']
      td
        = bm['stime']
      td
        = bm['total']
      td
        = bm['real']

app/views/battles/count.js.slim
- result = @battle.result.nil? ? nil : JSON.parse(@battle.result, quirks_mode: true)
- if result.is_a?(Array)
  | var content = "#{j(render 'table_result', result: result)}";
  - if params[:comment]
    | $('#comment_comment_battle_attributes_result').val('#{@battle.result.html_safe}');
  - else
    | content +=  "#{j(render 'get_link_form', battle: @battle)}";

- elsif result
  | var content = "#{j(render 'error_code', result: result)}";
- else
  | var content = "<div class='center-align'>#{@battle.errors.full_messages.to_sentence}</div>";

| $('#result').html(content)

app/views/battles/create.js.erb
<%- if @battle.persisted? %>
$('#get_link_form').html('<%= j render "provide_battle_link" %>')
<%- else %>
$('#get_link_form').append("<div class='message message-error'>Your battle description was broken.</div>")
<%- end %>

app/views/battles/new.html.slim
.center-align
  h2 Let's start code Battle
= simple_form_for @battle, url: count_battles_path, remote: true do |f|
  .row
    .col.s12.l6.input-field
      = f.input_field :before, size: '10x15', class: 'materialize-textarea'
      = f.label :before, 'Code team "Before"'
    .col.s12.l6.input-field
      = f.input_field :after, size: '10x15', class: 'materialize-textarea'
      = f.label :after, 'Code team "After"'
  .row
    .col.s12
      .center-align
        = f.button :button, 'start the battle', data: { 'disable-with': 'Finding best...' }, class: 'btn black'
.row
  .col.s12.l8.offset-l2
    #result

app/views/battles/show.html.slim
.center-align
  h2 Display code Battle
.row
  .col.s12.l6.input-field
    = label_tag :before, 'Code team "Before"'
    = text_area_tag :before, @battle.before, size: '10x15', disabled: true, class: 'materialize-textarea'
  .col.s12.l6.input-field
    = label_tag :after, 'Code team "After"'
    = text_area_tag :after, @battle.after, size: '10x15', disabled: true, class: 'materialize-textarea'
.row
  .col.s12.l8.offset-l2
    = render 'table_result', result: display_result(@battle)
- if current_user
  .divider
  #comments
    = render 'comments/comments', comments: @comments

app/views/comments/_comment.html.slim
.comment.grey.lighten-4.indent id="comment_#{comment.id}"
  .avatar.float-left.center-align
    div.user
      = image_tag(comment.user.image, size: '80x80')
      b= comment.user.nickname
  - if comment.text
    .comment-text
      = comment.text
- if battle = comment.comment_battle
  .row
    .col.s12.l6.input-field
      = text_area_tag :after, battle.after, size: '10x15', disabled: true, class: 'materialize-textarea'
    .col.s12.l6
      = render 'battles/table_result', result: display_result(battle)

hr

app/views/comments/_comments.html.slim
.row
  .btn-flat Comments
  = link_to 'New comment', '#comment_modal', class: 'modal-trigger waves-effect waves-light btn'
= render partial: 'comments/comment', collection: comments
= render 'comments/new_comment'

app/views/comments/_new_comment.html.slim
#comment_modal.modal.modal-fixed-footer
  #error.red.darken-4.center-align
  .modal-content
    = simple_form_for [@battle, @comment], remote: true do |f|
      = f.simple_fields_for :comment_battle do |b|
        .row
          .col.s12.l6.input-field
            = b.label :before, 'This code is bad'
            = b.input_field :before, value: @battle.before, class: 'materialize-textarea', disabled: true
          .col.s12.l6.input-field
            = b.label :after, 'I have better code'
            = b.input_field :after, class: 'materialize-textarea'
          = b.input :result, as: :hidden
          #result
        => button_tag :check, id: 'check_better', class: 'btn-bordered-radius'
        = button_tag :clear, id: 'clear_better', class: 'btn-bordered-radius purple lighten-5'
      .input-field
        = f.label :text, 'Message'
        = f.input_field :text, class: 'materialize-textarea'

  .modal-footer
    = button_tag 'add comment', id: 'add_comment', class: 'btn-flat btn-bordered-radius'

app/views/comments/create.js.slim
- if @comment.persisted?
  - @comment = Comment.new
  - @comment.build_comment_battle
  | $('#comment_modal').closeModal();
  | $('#comments').html("#{j render 'comments/comments', comments: @comments}");
  | $('.modal-trigger').leanModal();
- else
  | $('#error').append('#{@comment.errors[:comment].first}');

app/views/layouts/_flash_messages.html.slim
- flash.each do |type, message|
  .alert class="#{ alert(type) }"
    center
      = message

app/views/layouts/_session.html.slim
#navigation
  .fixed-action-btn.horizontal.click-to-toggle.top-navigation
    - if current_user
      a.btn-floating.btn-large.green.accent-4
        i.large.mdi-navigation-menu
      ul
        li
          = link_to sessions_destroy_path do
            i.fa.fa-sign-out.fa-2x
    - else
      a.btn-floating.btn-large.red.lighten-1
        i.large.mdi-navigation-menu
      ul
        li
          = link_to '/auth/github' do
            i.fa.fa-github.fa-2x

app/views/layouts/application.html.slim
doctype html
html
  head
    title Benchmarkit
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    .container
      = render 'layouts/session'
      = render 'layouts/flash_messages'
      = yield